Repository opencypher/cypher-for-apache-spark, pull requests merged in 2018-02, with the labels that each got.

#290 Remove unnecessary indirection in SparkSQLExprMapper
  caps-spark/src/main/scala/org/opencypher/caps/impl/spark/SparkSQLExprMapper.scala
Labels: refactoring

#279 Add SQL interaction API
  README.md
  caps-api/src/main/scala/org/opencypher/caps/api/graph/CypherSession.scala
  caps-api/src/main/scala/org/opencypher/caps/api/graph/PropertyGraph.scala
  caps-api/src/main/scala/org/opencypher/caps/impl/record/CypherRecords.scala
  caps-ir/src/main/scala/org/opencypher/caps/ir/impl/typer/fromFrontendType.scala
  caps-ir/src/main/scala/org/opencypher/caps/ir/impl/typer/toFrontendType.scala
  caps-ir/src/test/scala/org/opencypher/caps/ir/impl/typer/fromFrontendTypeTest.scala
  caps-ir/src/test/scala/org/opencypher/caps/ir/impl/typer/toFrontendTypeTest.scala
  caps-spark/src/main/scala/org/opencypher/caps/api/CAPSSession.scala
  caps-spark/src/main/scala/org/opencypher/caps/impl/spark/CAPSRecords.scala
  caps-spark/src/main/scala/org/opencypher/caps/impl/spark/CAPSSessionImpl.scala
  caps-spark/src/test/scala/org/opencypher/caps/demo/CypherSQLRoundtripExample.scala
  caps-spark/src/test/scala/org/opencypher/caps/demo/Example.scala
  caps-spark/src/test/scala/org/opencypher/caps/impl/record/EntityTableTest.scala
  caps-spark/src/test/scala/org/opencypher/caps/impl/spark/CAPSRecordsTest.scala
  caps-spark/src/test/scala/org/opencypher/caps/impl/spark/CAPSSessionImplTest.scala
  caps-spark/src/test/scala/org/opencypher/caps/impl/spark/acceptance/MatchBehaviour.scala
  caps-spark/src/test/scala/org/opencypher/caps/test/fixture/TeamDataFixture.scala
Labels: feature

#308 Fix documentation warnings
  okapi-api/src/main/scala/org/opencypher/okapi/api/configuration/Configuration.scala
  okapi-api/src/main/scala/org/opencypher/okapi/api/graph/CypherSession.scala
  okapi-api/src/main/scala/org/opencypher/okapi/api/graph/PropertyGraph.scala
  okapi-api/src/main/scala/org/opencypher/okapi/api/graph/QualifiedGraphName.scala
  okapi-api/src/main/scala/org/opencypher/okapi/api/io/conversion/NodeMapping.scala
  okapi-api/src/main/scala/org/opencypher/okapi/api/io/conversion/RelationshipMapping.scala
  okapi-api/src/main/scala/org/opencypher/okapi/api/value/CypherValue.scala
  okapi-relational/src/main/scala/org/opencypher/okapi/relational/api/physical/PhysicalOperatorProducer.scala
  okapi-relational/src/main/scala/org/opencypher/okapi/relational/api/physical/PhysicalPlannerContext.scala
  okapi-relational/src/main/scala/org/opencypher/okapi/relational/api/physical/RuntimeContext.scala
  spark-cypher-examples/README.md
  spark-cypher-examples/src/test/scala/org/opencypher/spark/examples/ReadmeTest.scala
  spark-cypher/src/main/scala/org/opencypher/spark/api/CAPSSession.scala
  spark-cypher/src/main/scala/org/opencypher/spark/impl/util/ZeppelinSupport.scala
  spark-cypher/src/main/scala/org/opencypher/spark/web/CAPSJsonSerialiser.scala
Labels: documentation, enhancement

#285 Update dependencies
  okapi-api/pom.xml
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/IRBuilder.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/typer/SchemaTyper.scala
  okapi-relational/pom.xml
  okapi-relational/src/main/scala/org/opencypher/okapi/relational/impl/table/InternalHeader.scala
  pom.xml
Labels: build, enhancement

#310 Fix example code
  spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/CypherSQLRoundtripExample.scala
Labels: bug

#311 Add sonatype required fields to project pom
  pom.xml
Labels: build, enhancement
