Repository opencypher/cypher-for-apache-spark, pull requests merged in 2018-04, with the labels that each got.

#337 Bugfixes for CAPSScanGraph
  spark-cypher/src/main/scala/org/opencypher/spark/impl/CAPSScanGraph.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/CAPSGraphTest.scala
Labels: bug

#338 Construct properties
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/api/IRElement.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/api/expr/Expr.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/api/pattern/Pattern.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/ExpressionConverter.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/IRBuilder.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/IRBuilderContext.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/PatternConverter.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/typer/SchemaTyper.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/util/VarConverters.scala
  okapi-ir/src/test/scala/org/opencypher/okapi/ir/impl/IrBuilderTest.scala
  okapi-ir/src/test/scala/org/opencypher/okapi/ir/impl/IrTestSuite.scala
  okapi-ir/src/test/scala/org/opencypher/okapi/ir/impl/PatternConverterTest.scala
  okapi-logical/src/main/scala/org/opencypher/okapi/logical/impl/LogicalPlanner.scala
  spark-cypher/src/main/scala/org/opencypher/spark/impl/physical/operators/BinaryOperators.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/acceptance/MultipleGraphBehaviour.scala
Labels: feature

#336 Refining data source API interactions
  README.md
  okapi-api/src/main/scala/org/opencypher/okapi/api/graph/CypherSession.scala
  okapi-api/src/main/scala/org/opencypher/okapi/api/graph/QualifiedGraphName.scala
  okapi-api/src/main/scala/org/opencypher/okapi/api/table/CypherRecords.scala
  okapi-api/src/main/scala/org/opencypher/okapi/impl/io/SessionGraphDataSource.scala
  okapi-api/src/test/scala/org/opencypher/okapi/api/graph/CypherSessionTest.scala
  okapi-api/src/test/scala/org/opencypher/okapi/api/graph/QualifiedGraphNameTest.scala
  okapi-api/src/test/scala/org/opencypher/okapi/impl/io/SessionGraphDataSourceTest.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/api/IRElement.scala
  spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/CaseClassExample.scala
  spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/CypherSQLRoundtripExample.scala
  spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/DataSourceExample.scala
  spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/GraphXPageRankExample.scala
  spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/MultipleGraphExample.scala
  spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/Neo4jWorkflow.scala
  spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/RecommendationExample.scala
  spark-cypher-examples/src/test/scala/org/opencypher/spark/examples/MasterExampleTest.scala
  spark-cypher/src/main/scala/org/opencypher/spark/api/CAPSSession.scala
  spark-cypher/src/main/scala/org/opencypher/spark/api/io/file/FileCsvGraphDataSource.scala
  spark-cypher/src/main/scala/org/opencypher/spark/api/io/hdfs/HdfsCsvGraphDataSource.scala
  spark-cypher/src/main/scala/org/opencypher/spark/api/io/neo4j/CommunityNeo4jGraphDataSource.scala
  spark-cypher/src/main/scala/org/opencypher/spark/demo/CSVDemo.scala
  spark-cypher/src/main/scala/org/opencypher/spark/impl/CAPSRecords.scala
  spark-cypher/src/main/scala/org/opencypher/spark/impl/CAPSSessionImpl.scala
  spark-cypher/src/test/scala/org/opencypher/spark/api/io/file/FileCsvGraphDataSourceTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/api/io/hdfs/HdfsCsvGraphDataSourceTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/api/io/neo4j/CommunityNeo4JGraphDataSourceTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/api/schema/TestGraphSchemaTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/CAPSGraphTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/CAPSRecordsPrinterTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/CAPSRecordsTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/CAPSSessionImplTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/CAPSUnionGraphTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/acceptance/CatalogDDLBehaviour.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/acceptance/MultipleGraphBehaviour.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/io/hdfs/CsvGraphWriterHDFSTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/io/hdfs/CsvGraphWriterLocalFSTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/physical/PhysicalOptimizerTest.scala
  spark-cypher/src/test/scala/org/opencypher/spark/test/fixture/CAPSSessionFixture.scala
  spark-cypher/src/test/scala/org/opencypher/spark/test/fixture/GraphConstructionFixture.scala
Labels: enhancement

#344 Implement COPY OF
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/api/expr/Expr.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/api/pattern/Pattern.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/IRBuilder.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/PatternConverter.scala
  okapi-ir/src/main/scala/org/opencypher/okapi/ir/impl/parse/rewriter/extractSubqueryFromPatternExpression.scala
  okapi-ir/src/test/scala/org/opencypher/okapi/ir/impl/IrBuilderTest.scala
  okapi-ir/src/test/scala/org/opencypher/okapi/ir/impl/IrTestSuite.scala
  okapi-ir/src/test/scala/org/opencypher/okapi/ir/impl/PatternConverterTest.scala
  okapi-ir/src/test/scala/org/opencypher/okapi/ir/test/support/creation/propertygraph/TestPropertyGraphFactory.scala
  okapi-logical/src/main/scala/org/opencypher/okapi/logical/impl/LogicalOperator.scala
  okapi-logical/src/main/scala/org/opencypher/okapi/logical/impl/LogicalPlanner.scala
  okapi-relational/src/main/scala/org/opencypher/okapi/relational/impl/table/InternalHeader.scala
  okapi-relational/src/main/scala/org/opencypher/okapi/relational/impl/table/RecordHeader.scala
  pom.xml
  spark-cypher/src/main/scala/org/opencypher/spark/impl/physical/operators/BinaryOperators.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/acceptance/MultipleGraphBehaviour.scala
Labels: feature

#360 Dynamically compute printed column widths
  okapi-api/src/main/scala/org/opencypher/okapi/api/value/CypherValue.scala
  okapi-api/src/main/scala/org/opencypher/okapi/impl/table/RecordsPrinter.scala
  okapi-api/src/main/scala/org/opencypher/okapi/impl/util/PrintOptions.scala
  spark-cypher/src/test/scala/org/opencypher/spark/impl/CAPSRecordsPrinterTest.scala
Labels: bug, enhancement

#357 Escape quotation marks in Cypher strings
  okapi-api/src/main/scala/org/opencypher/okapi/api/value/CypherValue.scala
  spark-cypher/src/test/scala/org/opencypher/spark/api/value/CAPSValueToStringTest.scala
Labels: bug

#374 Rework license listing and profiles
  .travis.yml
  licensecheck-config/README.adoc
  pom.xml
  scripts/release/src/main/scala/org/opencypher/github/release/CreateGitHubRelease.scala
  spark-cypher-examples/pom.xml
  spark-cypher/LICENSES.txt
  spark-cypher/NOTICE.txt
Labels: build, packaging

#368 Compute join fields on slot contents in OPTIONAL MATCH
  okapi-relational/src/main/scala/org/opencypher/okapi/relational/impl/physical/PhysicalPlanner.scala
  spark-cypher-tck/src/test/resources/scenario_blacklist
  spark-cypher/src/test/scala/org/opencypher/spark/impl/acceptance/OptionalMatchBehaviour.scala
Labels: bug
