Repository opencypher/cypher-for-apache-spark, pull requests merged in 2018-05, with the labels that each got.

#417 Clean up Neo4jConfig
  spark-cypher-examples/src/test/scala/org/opencypher/spark/examples/MasterExampleTest.scala
  spark-cypher/src/main/scala/org/opencypher/spark/api/io/neo4j/Neo4jConfig.scala
  spark-cypher/src/main/scala/org/opencypher/spark/impl/io/neo4j/Neo4jGraph.scala
  spark-cypher/src/main/scala/org/opencypher/spark/impl/io/neo4j/Neo4jGraphLoader.scala
Labels: enhancement, refactoring

#428 Develop PGDSAcceptance
  okapi-testing/src/main/scala/org/opencypher/okapi/testing/PGDSAcceptance.scala
Labels: enhancement, test

#436 Cypher type name parser
  okapi-api/src/main/scala/org/opencypher/okapi/api/types/CypherType.scala
  okapi-api/src/test/scala/org/opencypher/okapi/api/types/CypherTypesTest.scala
  okapi-ir/src/test/scala/org/opencypher/okapi/ir/impl/block/TypedMatchBlockTest.scala
  spark-cypher-testing/pom.xml
Labels: NOT READY FOR MERGE
